version: '3'

services:
    task_3:
        image: node:latest
        working_dir: /json_servak
        volumes:
        - ./:/json_servak
        ports: 
        - 3000:3000
        command: bash script_pipe.sh
    